### ISSUE TITLE
Some cleanup needed after item removal

### ISSUE THREAD

**Issue by Hypnosphi** [cyclejs/collection#1]
When you remove an item, `reducers` stream keeps imitating that item's sinks. This will inevitably lead to memory leaks.

**Comment by Widdershin** [comment]
You're totally correct. The handler streams should probably be stored in a collection and passed through, keyed on id, so they can be disposed later.

If you want to take a crack at implementing this, I welcome your pull request 😃

**Comment by Hypnosphi** [comment]
Here it is https://github.com/cyclejs/collection/pull/2

**Comment by Widdershin** [comment]
I think this is done! Thanks @Hypnosphi
