### ISSUE TITLE
Port Cycle TodoMVC to use Collection

### ISSUE THREAD

**Issue by Widdershin** [cyclejs/collection#21]
staltz has requested that we port [TodoMVC](https://github.com/cyclejs/todomvc-cycle) to use `Collection`.

Unfortunately I have too many things on my plate right now, but I would love it if anyone would like to have a go at this.

@Hypnosphi, would you be interested?

**Comment by Hypnosphi** [comment]
I'll go for it

**Comment by Widdershin** [comment]
Awesome 👍 happy to review if you like 😄

**Comment by Hypnosphi** [comment]
https://github.com/cyclejs/todomvc-cycle/pull/34

**Comment by Widdershin** [comment]
Awesome, thanks so much for taking care of that. I left a comment on that PR.

**Comment by FeliciousX** [comment]
Isn't this done? :D

**Comment by Widdershin** [comment]
Merged thanks to @Frikki :smile:
