### ISSUE TITLE
MakeCollection seem dose not work for me

### ISSUE THREAD

**Issue by addhome2001** [cyclejs/collection#27]
I'm a beginner of cyclejs,  because i using other stream library than xstream,  so i
implement the `makeCollection` function.

 But it's seem dose not work for me. Maybe i dose something wrong? 

The `TodoItem` 's arguments `source` just  contain DOM object, but no `add$` stream.

This is my code snippet.
```
import Cycle from '@cycle/rxjs-run';
import {div, h ,input, button,ul, makeDOMDriver} from '@cycle/dom';
import { makeCollection } from '@cycle/collection';
import rxjsAdapter from '@cycle/rxjs-adapter';

const Collection = makeCollection(rxjsAdapter);

function TodoItem(source) {
  const removeItem$ = source.DOM.select('.remove').events('click').startWith("");
  const TodoItem$ = item => h('li.item', [item, h('button.remove','X')]);

  const sink = {
    DOM: source.state$.map(TodoItem),
    remove$: removeItem$
  }

  return sink
}

function TodoItems({ DOM, props: props$ }) {
  const state$ = props$.map(val => val.trim());
  const todoListItems$ = Collection(TodoItem, { DOM }, state$, item => item.remove$);
  const vdom$ = Collection.pluck(todoListItems$, item => item.DOM);

  const sink = {
    DOM: vdom$
  }

  return sink;
}
```
Can somebody give me a bit of help?

**Comment by Hypnosphi** [comment]
What's in props$?

**Comment by Hypnosphi** [comment]
If you want an additional source on `sources.state$`, you must create it explicitly:

```js
const add$ = props$.map(val => ({
    state$: Rx.Observable.of(val.trim())
}));
```

**Comment by Widdershin** [comment]
Also:
```
  const sink = {
    DOM: source.state$.map(TodoItem),
    remove$: removeItem$
  }
```

`TodoItem` there should probably be `TodoItem$`. It might be worth renaming `TodoItem$` to `view` or `renderTodo` since it's not a stream. (`$` should be read as "stream")

**Comment by addhome2001** [comment]
@Hypnosphi Obviously, the `add$` stream should contain Object(property is Observable) instead of String. Thanks a lot. You saved my time!!!!!!!

@Widdershin Maybe i missed it. I will be more careful next time.
