### ISSUE TITLE
Update to support latest versions of Cycle (Cycle Unified)

### ISSUE THREAD

**Issue by bbarker** [cyclejs/collection#35]
Pulling in collection seems to be causing me to get the following error (as I don't appear to have anything else that relies on xstream-adapter, which seems to be no-longer supported in Cycle Unified): `node_modules/@cycle/xstream-adapter/lib/index.d.ts(1,31): error TS2307: Cannot find module '@cycle/base'`.

**Comment by FeliciousX** [comment]
fixed in #37
