### ISSUE TITLE
Item's sink completion breaks everything

### ISSUE THREAD

**Issue by Hypnosphi** [cyclejs/collection#6]
At first I've noticed that my PR https://github.com/cyclejs/collection/pull/2 broke the example: when you remove one item, you can't remove the others. The reason is that completing the `handler$` leads to completion of `reducers` which then stop reacting to any sinks.

And the important thing here is that components might as well complete their sinks internally, and that shouldn't lead to the entire collection being frozen.

**Comment by Hypnosphi** [comment]
One possible solution is to use explicit subscription+proxying instead of `imitate`

**Comment by Widdershin** [comment]
I had also noticed this. I'm happy to go back to an explicit subscription, that's how it was before. Were you interested in making a pull request for this?

**Comment by Hypnosphi** [comment]
Working on that right now =) I also would like to wrap the Collection function a bit, to hide the non-public arguments.

**Comment by Widdershin** [comment]
I totally agree about wrapping it to provide a smaller public interface.

**Comment by FeliciousX** [comment]
With the latest xstream update, do you think it's safe to use back imitate?

**Comment by Hypnosphi** [comment]
Not unless it supports unsubscribing

**Comment by Hypnosphi** [comment]
In fact, current realization of `imitate` isn't applicable to multiple stream imitation. When you call `imitate` repeatedly, it just switches to the new stream.

**Comment by Hypnosphi** [comment]
There's a chance we'll be able to `imitate` a merged handlers stream each time an item is added to / removed from collection. Let's just wait until https://github.com/staltz/xstream/issues/49#issuecomment-224899640 resolves.

**Comment by staltz** [comment]
I'm coming to the realization that https://github.com/staltz/xstream/issues/49 may not actually be a bug, since in Cycle.js code, `imitate()` will be in `main()` and drivers will add listeners, meaning: listeners always added after `imitate`. Also, with xstream we want to eliminate worrying about the subscription moment.

So instead of that, how can I help with your use case here? What code should I look at which uses imitate here?

**Comment by Hypnosphi** [comment]
The thing is that before constructing a stream of collection states, we need a reference to stream of all `remove` actions/reducers triggered by items (which are not yet present at the moment of collection initialization. Here you can see how we switched from `imitate` to `addListener` because of the given issue: https://github.com/cyclejs/collection/pull/7/files#diff-d2dbe7779d59d4dd594e92248caba0a5L47

So now we're starting listening inside the app, and that's really not cool

**Comment by staltz** [comment]
I'm almost certain something is wrong in that implementation. shamefullySendNext is a sign of that. I'll look at it carefully later/soon.

**Comment by Widdershin** [comment]
@Hypnosphi made a proposal a while back (which I now can't find), that instead of using the sink handlers approach, each item can instead return a reducers/action stream directly, and when that stream completes the item would be removed.

That seems like it would allow us to drop the shamefullySendNext, and do things in a bit more reactive way. Maybe that's the right path forward

**Comment by Hypnosphi** [comment]
It's here https://github.com/cyclejs/collection/pull/2#issue-156735210

**Comment by Hypnosphi** [comment]
Maybe we should comletely rethink what cycle-collection should do. Maybe it should itself costruct a stream of collections given all the present arguments plus an `add$`, whose optional values are additional sources.

**Comment by Widdershin** [comment]
Ooh that's an interesting idea.

I'm entirely open to that approach if the ergonomics work out better. Could you make an example of what usage would look like? I'm especially interested in how removal might be handled

**Comment by Hypnosphi** [comment]
```js
collection$ = Collection(
  Component,
  {DOM},
  add$: xs.of({prop$}),
  removeSinkName: 'remove$' // this might be a default
);
```

Removes are handled just like before, but you need not to declare remove handler explicitly, just provide the relevant sink name. Internally, `Collection` creates a reducers stream by merging `add$` mapped to additions and merged `remove$`, imitated as in my comment above, mapped to removals.

**Comment by Widdershin** [comment]
I'm very open to this move. It would definitely make documenting this
library a lot easier.

Are you interested in having a go at implementing? I'll merge the gather PR
now so you can build on top of your like.

**Comment by Hypnosphi** [comment]
I certainly am

**Comment by Widdershin** [comment]
Great! I look forward to reviewing the PR! 😺 

Also, have you seen this? https://github.com/motorcyclejs/collection

Inspired by but taking our approach a step further. Seems like there is some stuff we can learn!

**Comment by Hypnosphi** [comment]
Looks a bit overengineered to me, but there are definitely some ideas to borrow.

**Comment by axefrog** [comment]
@Hypnosphi Care to elaborate?

**Comment by Hypnosphi** [comment]
I like an idea of a collection as a list, not a tuple or whatever

**Comment by axefrog** [comment]
@Hypnosphi I don't want to derail this thread, so you're welcome to open an issue or discuss it with me on Gitter or something, but I don't think you really understand what's there or what the goal was.

**Comment by Hypnosphi** [comment]
I believe this is closed with https://github.com/cyclejs/collection/pull/14
